import type { Metadata } from "next";
import { Inter, Titillium_Web } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const TitilliumWeb = Titillium_Web({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Boris Rakhamimov Gallery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={TitilliumWeb.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
